export const ADD_RESOURCES = "ADD_RESOURCES";
export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const AGENTS_LOADED = "AGENTS_LOADED";

export const TURN_ON_COVER = "TURN_ON_COVER";
export const TURN_OFF_COVER = "TURN_OFF_COVER";